In [63]:
from tensorflow.keras.layers import Input,Conv2D, MaxPooling2D, Flatten, Dropout, Dense, Activation

In [61]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.datasets import mnist
from matplotlib import pyplot as plt
import numpy as np

In [33]:
x_1 = np.random.normal(5,5,(5,5))

In [34]:
x_1

array([[ 8.42750765,  2.82586776, -0.92368261, -3.66713334,  8.76402754],
       [12.60003291, -4.31533082,  7.8501249 ,  8.32582128,  9.10745287],
       [12.88325229,  3.44328612,  9.28381446, -2.10268023, -6.82270436],
       [ 0.95754314,  3.62443561, 12.33756733,  1.97012565,  3.46507781],
       [ 1.2009839 ,  5.2541294 , -1.86643773,  5.65092031,  3.6132708 ]])

In [35]:
x_1 = x_1.reshape(5,5,1)

In [40]:
x_1[0,1,0]

2.8258677645924424

In [36]:
x_1

array([[[ 8.42750765],
        [ 2.82586776],
        [-0.92368261],
        [-3.66713334],
        [ 8.76402754]],

       [[12.60003291],
        [-4.31533082],
        [ 7.8501249 ],
        [ 8.32582128],
        [ 9.10745287]],

       [[12.88325229],
        [ 3.44328612],
        [ 9.28381446],
        [-2.10268023],
        [-6.82270436]],

       [[ 0.95754314],
        [ 3.62443561],
        [12.33756733],
        [ 1.97012565],
        [ 3.46507781]],

       [[ 1.2009839 ],
        [ 5.2541294 ],
        [-1.86643773],
        [ 5.65092031],
        [ 3.6132708 ]]])

In [12]:
x_2 = np.ones((4,))

In [13]:
x_2

array([1., 1., 1., 1.])

In [18]:
x_1.shape == x_2.shape

False

In [102]:
(Xtrain_full, ytrain_full), (Xtest, ytest) = mnist.load_data()
Xvalid, Xtrain = Xtrain_full[:5000] / 255.0, Xtrain_full[5000:] / 255.0
yvalid, ytrain = ytrain_full[:5000] / 10.0, ytrain_full[5000:] / 10.0
Xtest = Xtest / 255.0

In [100]:
ytrain.max()

0.9

In [96]:
Xtrain.shape

(55000, 28, 28)

In [81]:
Xtrain_reshape = Xtrain.reshape(-1,28,28,1)
Xvalid_reshape = Xvalid.reshape(-1,28,28,1)

In [83]:
Xtrain_reshape[0].shape

(28, 28, 1)

In [87]:
# Geron implementation
model = Sequential([
    Input(shape=[28,28,1]),
    Conv2D(64, 7, activation='relu', padding="same"),
    MaxPooling2D(2),
    Flatten(),
    Dense(10, activation='relu'),
    Dropout(0.5),
    Dense(10, activation='softmax')        
])

In [105]:
# KR spiced implementation 9.5.4
model2 = Sequential([
    Conv2D(5, kernel_size=(3,3), strides=(2,2),
          padding='same', activation='relu',
          input_shape=(28,28,1)),
    
    MaxPooling2D(pool_size=(3,3), strides=(2,2), padding='same'),
                
    Flatten(),
    
    Dense(units = 10, activation='relu'),
    Dense(units = 1, activation ='softmax')
    
])

In [106]:
model2.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 14, 14, 5)         50        
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 7, 7, 5)           0         
_________________________________________________________________
flatten_5 (Flatten)          (None, 245)               0         
_________________________________________________________________
dense_10 (Dense)             (None, 10)                2460      
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 11        
Total params: 2,521
Trainable params: 2,521
Non-trainable params: 0
_________________________________________________________________


In [89]:
model.compile(loss="sparse_categorical_crossentropy",
             optimizer="sgd",
             metrics=["accuracy"])

In [107]:
model2.compile(loss="sparse_categorical_crossentropy",
             optimizer="sgd",
             metrics=["accuracy"])

In [108]:
history = model2.fit(Xtrain_reshape, ytrain, epochs=5, validation_data=(Xvalid, yvalid))

Epoch 1/5
1713/1719 [============================>.] - ETA: 0s - loss: 0.0000e+00 - accuracy: 0.0000e+00

ValueError: in user code:

    /opt/anaconda3/envs/dl/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:1233 test_function  *
        return step_function(self, iterator)
    /opt/anaconda3/envs/dl/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:1224 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /opt/anaconda3/envs/dl/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /opt/anaconda3/envs/dl/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /opt/anaconda3/envs/dl/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    /opt/anaconda3/envs/dl/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:1217 run_step  **
        outputs = model.test_step(data)
    /opt/anaconda3/envs/dl/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:1183 test_step
        y_pred = self(x, training=False)
    /opt/anaconda3/envs/dl/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:998 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /opt/anaconda3/envs/dl/lib/python3.7/site-packages/tensorflow/python/keras/engine/input_spec.py:239 assert_input_compatibility
        str(tuple(shape)))

    ValueError: Input 0 of layer sequential_6 is incompatible with the layer: : expected min_ndim=4, found ndim=3. Full shape received: (None, 28, 28)
